layout_spectrum: 0.5308955474756658
typography_spectrum: 0.8496476309373975
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.15331931319087744
  lightness: 0.32387023232877254
  saturation: 0.3785824505612254
  rhythmicContrast: 0.7162427580915391
name: Stone Carving Sculptures
favicon: null
title: Stone Carving Sculptures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
