name: Stone Carving Sculptures
favicon: null
layout_spectrum: 0.9222134798765182
typography_spectrum: 0.5049663246609271
title: Stone Carving Sculptures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.6664031764958054
  lightness: 0.2785366775933653
  saturation: 0.15020227245986462
  rhythmicContrast: 0.043098370311781764
purpose: []
