typography_spectrum: 0.8107737370301038
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.18252301984466612
  lightness: 0.8851327197626233
  saturation: 0.9772155652754009
  rhythmicContrast: 0.22025806712917984
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6206319527700543
analytics:
  google: UA-35516913-1
  facebook: null
  twitter: null
name: Stone Carving Sculptures
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: More Stone Carvings (lots)
    url: 'http://richokun.shutterfly.com/'
    type: external
  - name: Moses
    id: 688c354e-f321-42a9-a5d2-828e6e48422c
    type: content
  - name: Father
    id: 0147993a-2f13-4655-8db0-1491dc16ed1d
    type: content
  - name: Dragonfly/Butterfly
    id: 56285897-f18a-4c9a-8258-dc95a8b0d88a
    type: content
  - name: Wisdom
    id: 6ab3c9cb-e88c-49cf-834d-88d9bcbc45fd
    type: content
  - name: YHVH
    id: d731599b-4507-4072-8367-28359027ca02
    type: content
favicon: null
title: Stone Carving Sculptures
purpose: []
