name: Homepage1
favicon: null
layout_spectrum: 0.40518
typography_spectrum: 0.93216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070713'
    - '#9a9083'
    - '#dccfc9'
    - '#534949'
    - '#fffdf9'
  brandStrength: 0.25
  lightness: 0.10701844445429742
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
