name: Stone Carving Sculptures
favicon: null
layout_spectrum: 0.43405
typography_spectrum: 0.43411
title: Stone Carving Sculptures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3eef0'
    - '#b9bab4'
    - '#270e0a'
    - '#903e28'
    - '#86887b'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
