typography_spectrum: 0.8496476309373975
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.15331931319087744
  lightness: 0.32387023232877254
  saturation: 0.3785824505612254
  rhythmicContrast: 0.7162427580915391
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5308955474756658
analytics:
  google: null
  facebook: null
  twitter: null
name: Stone Carving Sculptures
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: More Stone Carvings (lots)
    url: 'http://richokun.shutterfly.com/'
    type: external
  - name: Lamed Vav
    id: 847b8d03-bae4-42e9-9b8c-1663b7b1c285
    type: content
  - name: YHVH man
    id: da07ca1d-3247-40a2-871d-0ccc9e828ffa
    type: content
  - name: Vey Ha Ya
    id: f811b830-b515-4d61-bb27-146c12b7eef8
    type: content
  - name: Principle
    id: 15bcbdba-5c7d-4a43-af0c-4e4352de8369
    type: content
  - name: Love
    id: 2d07139e-cae4-4bec-b7bc-41657c970bb1
    type: content
  - name: Life
    id: bc0eaab8-f6df-402d-9091-915e047d7377
    type: content
  - name: Jayle el
    id: d026daad-b90b-4acb-b838-a33164ae12bd
    type: content
  - name: Healing
    id: 47429fd4-a95e-4ad5-9d03-500b24320181
    type: content
  - name: Efraim
    id: eaf54b75-6ea4-4616-9e2e-d4d44b1dff0c
    type: content
  - name: Angel
    id: 3b219d2e-8dbd-4e3b-b024-50ac88b3c37e
    type: content
  - name: 'Aladiah '
    id: a5c2c406-4d38-4211-80cc-13f3a5df8637
    type: content
  - name: Shalom
    id: 6e40e2d0-6442-4d4a-974f-b63924ce4c05
    type: content
  - name: Mother
    id: db2e64d2-beff-42b6-b3fa-1f1421377c3f
    type: content
favicon: null
title: Stone Carving Sculptures
purpose: []
