typography_spectrum: 0.8107737370301038
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.18252301984466612
  lightness: 0.8851327197626233
  saturation: 0.9772155652754009
  rhythmicContrast: 0.22025806712917984
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6206319527700543
analytics:
  google: UA-35516913-1
  facebook: null
  twitter: null
name: Stone Carving Sculptures
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Click for More Stone Carvings (lots)
    url: 'http://richokun.shutterfly.com/'
    type: external
favicon: null
title: Stone Carving Sculptures
purpose: []
